spring:
  data:
    mongodb:
      uri: mongodb+srv://yash:yash@cluster0.5sgqa.mongodb.net/journaldb?retryWrites=true&w=majority
      auto-index-creation: true
  main:
    allow-circular-references: true

server:
  port: 8080

logging:
  level:
    com:
      devinfusion:
        journalApp: DEBUG
